### ISSUE TITLE
fastq.gz convert to bam

### ISSUE THREAD

**Issue by ESWRKJ** [jmestret/BioToyBox#1]
@jmestret 
Hi,  I use the PacBio RS II It's read of inserts(ROI) fq.gz 。Can I use ccs.bam as reference to convert fg.gz to bam？

**Comment by jmestret** [comment]
Hi @ESWRKJ ,

It seems you're looking into the [Convert2PacBioBam](https://github.com/jmestret/BioToyBox/blob/main/scripts/README.md#convert2pacbiobam) script. I developed this script for a specific situation where I had simulated PacBio reads in FASTA format. Formatting them into PacBio-specific BAM was necessary to smoothly follow the Iso-Seq pipeline.

If this script suits your needs, simply provide the FASTA or FASTQ file you want to re-format, a real BAM file (from which the script will copy special fields), and specify the output name. In my case, I used a 'flnc.bam' as template but I believe your 'ccs.bam' should work just as well.

The script processes line by line and might take some time, as it's a basic tool. You can also explore splitting the FASTQ if needed. Keep in mind, it's been a while since I last used the script, so I hope it still performs smoothly. If you find it useful and decide to make any adjustments or improvements, we would sincerely appreciate it if you could submit a pull request.

Best of luck with your work!
